### ISSUE TITLE
step 4  when operate command $ npm start 

### ISSUE THREAD

**Issue by ewrfedf** [fbsamples/f8app#13]

**Comment by ewrfedf** [comment]
`zcpdeMacBook-Pro:f8app Zheng$ npm start

> F8v2@0.0.1 start /Users/Zheng/React-Native/f8app
> babel-node ./server/server.js

module.js:341
    throw err;
    ^

Error: Cannot find module '/Users/Zheng/React-Native/f8app/node_modules/grpc/src/node/extension_binary/grpc_node.node'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/Zheng/React-Native/f8app/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
    at Module._compile (module.js:413:34)
    at Module._extensions`

**Comment by frantic** [comment]
Looks like your `npm install` might have failed. Try `rm -rf node_modules && npm install`. Please reopen if that doesn't help.

**Comment by xsgkaka** [comment]
do not use cnpm,and re install
