### ISSUE TITLE
cannot find entry file index.ios.js in any of the roots

### ISSUE THREAD

**Issue by huangjianke** [fbsamples/f8app#130]
Help!!!

![image](https://cloud.githubusercontent.com/assets/8692455/19829497/f55b1940-9e15-11e6-8467-107411250ea4.png)

**Comment by haikyuu** [comment]
There is an answer for this problem in [stackoverflow](http://stackoverflow.com/questions/29388704/react-cannot-find-entry-file-in-any-of-the-roots)
I think we can close this issue

**Comment by proactive-solutions** [comment]
Facing the same issue

![simulator screen shot 09-jun-2017 2 39 59 pm](https://user-images.githubusercontent.com/13619716/26968932-863732d6-4d21-11e7-9920-60d826ee8d34.png)

**Comment by proactive-solutions** [comment]
React packager ready.

Loading dependency graph, done.
error: bundling: Error
    at DependencyGraph._getAbsolutePath (/Users/pawan.sharma/React_Native/FirstNavaigation/node_modules/react-native/packager/src/node-haste/DependencyGraph.js:280:11)
    at DependencyGraph.getDependencies (/Users/pawan.sharma/React_Native/FirstNavaigation/node_modules/react-native/packager/src/node-haste/DependencyGraph.js:218:26)
    at Resolver.getDependencies (/Users/pawan.sharma/React_Native/FirstNavaigation/node_modules/react-native/packager/src/Resolver/index.js:107:27)
    at /Users/pawan.sharma/React_Native/FirstNavaigation/node_modules/react-native/packager/src/Bundler/index.js:591:37
    at Generator.next (<anonymous>)
    at step (/Users/pawan.sharma/React_Native/FirstNavaigation/node_modules/react-native/packager/src/Bundler/index.js:12:445)
    at /Users/pawan.sharma/React_Native/FirstNavaigation/node_modules/react-native/packager/src/Bundler/index.js:12:605
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
Bundling `index.ios.js`  0.0% (0/1), failed.
error: bundling: Error
    at DependencyGraph._getAbsolutePath (/Users/pawan.sharma/React_Native/FirstNavaigation/node_modules/react-native/packager/src/node-haste/DependencyGraph.js:280:11)
    at DependencyGraph.getDependencies (/Users/pawan.sharma/React_Native/FirstNavaigation/node_modules/react-native/packager/src/node-haste/DependencyGraph.js:218:26)
    at Resolver.getDependencies (/Users/pawan.sharma/React_Native/FirstNavaigation/node_modules/react-native/packager/src/Resolver/index.js:107:27)
    at /Users/pawan.sharma/React_Native/FirstNavaigation/node_modules/react-native/packager/src/Bundler/index.js:591:37
    at Generator.next (<anonymous>)
    at step (/Users/pawan.sharma/React_Native/FirstNavaigation/node_modules/react-native/packager/src/Bundler/index.js:12:445)
    at /Users/pawan.sharma/React_Native/FirstNavaigation/node_modules/react-native/packager/src/Bundler/index.js:12:605
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
Bundling `index.ios.js`  0.0% (0/1), failed.
error: bundling: Error
    at DependencyGraph._getAbsolutePath (/Users/pawan.sharma/React_Native/FirstNavaigation/node_modules/react-native/packager/src/node-haste/DependencyGraph.js:280:11)
    at DependencyGraph.getDependencies (/Users/pawan.sharma/React_Native/FirstNavaigation/node_modules/react-native/packager/src/node-haste/DependencyGraph.js:218:26)
    at Resolver.getDependencies (/Users/pawan.sharma/React_Native/FirstNavaigation/node_modules/react-native/packager/src/Resolver/index.js:107:27)
    at /Users/pawan.sharma/React_Native/FirstNavaigation/node_modules/react-native/packager/src/Bundler/index.js:591:37
    at Generator.next (<anonymous>)
    at step (/Users/pawan.sharma/React_Native/FirstNavaigation/node_modules/react-native/packager/src/Bundler/index.js:12:445)
    at /Users/pawan.sharma/React_Native/FirstNavaigation/node_modules/react-native/packager/src/Bundler/index.js:12:605
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
Bundling `index.ios.js`  0.0% (0/1), failed.
error: bundling: Error
    at DependencyGraph._getAbsolutePath (/Users/pawan.sharma/React_Native/FirstNavaigation/node_modules/react-native/packager/src/node-haste/DependencyGraph.js:280:11)
    at DependencyGraph.getDependencies (/Users/pawan.sharma/React_Native/FirstNavaigation/node_modules/react-native/packager/src/node-haste/DependencyGraph.js:218:26)
    at Resolver.getDependencies (/Users/pawan.sharma/React_Native/FirstNavaigation/node_modules/react-native/packager/src/Resolver/index.js:107:27)
    at /Users/pawan.sharma/React_Native/FirstNavaigation/node_modules/react-native/packager/src/Bundler/index.js:591:37
    at Generator.next (<anonymous>)
    at step (/Users/pawan.sharma/React_Native/FirstNavaigation/node_modules/react-native/packager/src/Bundler/index.js:12:445)
    at /Users/pawan.sharma/React_Native/FirstNavaigation/node_modules/react-native/packager/src/Bundler/index.js:12:605
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
Bundling `index.ios.js`  0.0% (0/1), failed.


![screen shot 2017-06-09 at 2 41 57 pm](https://user-images.githubusercontent.com/13619716/26969008-d0fe9c14-4d21-11e7-8d8f-d3bfd4c371bc.png)

**Comment by kyle-ssg** [comment]
I seem to have also got this after upgrading to rn 0.45.0...

**Comment by matthewjamieson** [comment]
Just upgraded to 0.45 and got the exact same issue

**Comment by aorborc** [comment]
cd path/to/project && npm start

fixed this for me. 

Only issue is, I had to leave that terminal tab open.

**Comment by Lxxyx** [comment]
Same issue for me.

**Comment by ymotoba** [comment]
me too...

**Comment by Lxxyx** [comment]
I try to reinstall node_modules and solve this problem.

**Comment by UtenteBello** [comment]
same issue

**Comment by peteroid** [comment]
Experienced the issue with these setups,

```bash
# react-native-cli@2.0.1
react-native --version="0.45.0" MyProject
cd MyProject
react-native run-ios # issue occurred!
```
To overcome this, I need 2 terminals.

### Terminal A
```bash
#  this will start the packager instead of spawning a new one
yarn start
```

### Terminal B
```bash
react-native run-ios # no error ~
```

**Comment by uxitten** [comment]
run this command` npm start -- --reset-cache`

**Comment by iPopReact** [comment]
Facing same error.  npm start -- --reset-cache doesn't solve my issue.
React native version : 0.43.1
Any suggestion?
![simulator screen shot feb 8 2018 4 47 29 pm](https://user-images.githubusercontent.com/35257546/35970595-ee6873da-0cf0-11e8-8f03-74ec120b8dda.png)

**Comment by jiku** [comment]
Experienced this from using pnpm. Using yarn solved it. Possibly related to RN issues with [symlinks](https://github.com/facebook/metro/issues/1).

**Comment by PedroSolintel** [comment]
I'm also having the same error. None of the solutions here worked.
