### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by wayne-kim** [fbsamples/f8app#134]
I saw all tutorial - THE BASICS. and then i was going to see this app. but i got a install error.
i could not find what is problem.

My computer environment is following bellow.
window 10 pro 64bit
node v7.0.0
python 2.7.11
mongodb 3.2.10

this is my error mes

```
84811 silly install printInstalled
84812 verbose stack Error: Unsupported platform for fsevents@1.0.12: wanted {"name":"fsevents","version":"1.0.12","description":"Native Access to Mac OS-X FSEvents","main":"fsevents.js","dependencies":{"nan":"^2.3.0","node-pre-gyp":"^0.6.25"},"os":["darwin"],"engines":{"node":">=0.8.0"},"scripts":{"install":"node-pre-gyp install --fallback-to-build","prepublish":"if [ $(npm -v | head -c 1) -lt 3 ]; then exit 1; fi && npm dedupe","test":"tap ./test"},"binary":{"module_name":"fse","module_path":"./lib/binding/{configuration}/{node_abi}-{platform}-{arch}/","remote_path":"./v{version}/","package_name":"{module_name}-v{version}-{node_abi}-{platform}-{arch}.tar.gz","host":"https://fsevents-binaries.s3-us-west-2.amazonaws.com"},"repository":{"type":"git","url":"git+https://github.com/strongloop/fsevents.git"},"keywords":["fsevents","mac"],"author":{"name":"Philipp Dunkel","email":"pip@pipobscure.com"},"license":"MIT","bugs":{"url":"https://github.com/strongloop/fsevents/issues"},"homepage":"https://github.com/strongloop/fsevents","devDependencies":{"tap":"~0.4.8"},"readme":"# fsevents [![NPM](https://nodei.co/npm/fsevents.png)](https://nodei.co/npm/fsevents/)\n\nNative access to OS X FSEvents in [Node.js](http://nodejs.org/)\n\nThe FSEvents API in OS X allows applications to register for notifications of\nchanges to a given directory tree. It is a very fast and lightweight alternative\nto kqueue.\n\nThis is a low-level library. For a cross-compatible file watching module that\nuses fsevents, check out [Chokidar](https://www.npmjs.com/package/chokidar).\n\n* [Module Site & GitHub](https://github.com/strongloop/fsevents)\n* [NPM Page](https://npmjs.org/package/fsevents)\n\n## Installation\n\n\t$ npm install fsevents\n\n## Usage\n\n```js\nvar fsevents = require('fsevents');\nvar watcher = fsevents(__dirname);\nwatcher.on('fsevent', function(path, flags, id) { }); // RAW Event as emitted by OS-X\nwatcher.on('change', function(path, info) { }); // Common Event for all changes\nwatcher.start() // To start observation\nwatcher.stop()  // To end observation\n```\n\n### Events\n\n * *fsevent* - RAW Event as emitted by OS-X\n * *change* - Common Event for all changes\n * *created* - A File-System-Item has been created\n * *deleted* - A File-System-Item has been deleted\n * *modified* - A File-System-Item has been modified\n * *moved-out* - A File-System-Item has been moved away from this location\n * *moved-in* - A File-System-Item has been moved into this location\n\nAll events except *fsevent* take an *info* object as the second parameter of the callback. The structure of this object is:\n\n```js\n{\n  \"event\": \"<event-type>\",\n  \"id\": <eventi-id>,\n  \"path\": \"<path-that-this-is-about>\",\n  \"type\": \"<file|directory|symlink>\",\n  \"changes\": {\n    \"inode\": true, // Has the iNode Meta-Information changed\n    \"finder\": false, // Has the Finder Meta-Data changed\n    \"access\": false, // Have the access permissions changed\n    \"xattrs\": false // Have the xAttributes changed\n  },\n  \"flags\": <raw-flags>\n}\n```\n\n## MIT License\n\nCopyright (C) 2010-2014 Philipp Dunkel\n\nPermission is hereby granted, free of charge, to any person obtaining a copy\nof this software and associated documentation files (the \"Software\"), to deal\nin the Software without restriction, including without limitation the rights\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\ncopies of the Software, and to permit persons to whom the Software is\nfurnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in\nall copies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN\nTHE SOFTWARE.\n","readmeFilename":"Readme.md","bundleDependencies":["node-pre-gyp"],"_id":"fsevents@1.0.12","_shasum":"7929e211c0b31f37f2f0fc346f315e403d7ed33b","_resolved":"https://registry.npmjs.org/fsevents/-/fsevents-1.0.12.tgz","_from":"fsevents@>=1.0.0 <2.0.0","_inCache":true,"_requested":{"raw":"fsevents@https://registry.npmjs.org/fsevents/-/fsevents-1.0.12.tgz","scope":null,"escapedName":"fsevents","name":"fsevents","rawSpec":"https://registry.npmjs.org/fsevents/-/fsevents-1.0.12.tgz","spec":"https://registry.npmjs.org/fsevents/-/fsevents-1.0.12.tgz","type":"remote"},"_spec":"fsevents@https://registry.npmjs.org/fsevents/-/fsevents-1.0.12.tgz","_where":"D:\\LoopyWayne\\mobile\\workspace\\f8app-master","_args":[[{"raw":"fsevents@https://registry.npmjs.org/fsevents/-/fsevents-1.0.12.tgz","scope":null,"escapedName":"fsevents","name":"fsevents","rawSpec":"https://registry.npmjs.org/fsevents/-/fsevents-1.0.12.tgz","spec":"https://registry.npmjs.org/fsevents/-/fsevents-1.0.12.tgz","type":"remote"},"D:\\LoopyWayne\\mobile\\workspace\\f8app-master"]],"_shrinkwrap":null,"optionalDependencies":{}} (current: {"os":"win32","cpu":"x64"})
84812 verbose stack     at checkPlatform (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-install-checks\index.js:45:14)
84812 verbose stack     at thenWarnEngineIssues (C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:41:5)
84812 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\iferr\index.js:13:50
84812 verbose stack     at checkEngine (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-install-checks\index.js:24:10)
84812 verbose stack     at module.exports.isInstallable (C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:38:3)
84812 verbose stack     at actions.(anonymous function) (C:\Program Files\nodejs\node_modules\npm\lib\install\actions.js:52:14)
84812 verbose stack     at execAction (C:\Program Files\nodejs\node_modules\npm\lib\install\actions.js:114:7)
84812 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
84812 verbose stack     at Array.forEach (native)
84812 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
84813 verbose pkgid fsevents@1.0.12
84814 verbose cwd D:\LoopyWayne\mobile\workspace\f8app-master
84815 error Windows_NT 10.0.14393
84816 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
84817 error node v7.0.0
84818 error npm  v3.10.8
84819 error code EBADPLATFORM
84820 error notsup Unsupported platform for fsevents@1.0.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
84821 error notsup Valid OS:    darwin
84821 error notsup Valid Arch:  any
84821 error notsup Actual OS:   win32
84821 error notsup Actual Arch: x64
84822 verbose exit [ 1, true ]
```

**Comment by wayne-kim** [comment]
i thought that this app is set for iOS.
So I deleted "fsevents" dependency at npm-shrinkwrap file.
and then i run, "npm install". I could a install.
but I failed to build. so i saw a error message. "failed to finde Build Tools revision 23.0.2"
so i install the "Anroid SDK Build-tools" at SDK Manager and made API Level 23 AVD and run it.

```
:app:processDebugManifest
D:\LoopyWayne\mobile\workspace\f8app\android\app\src\main\AndroidManifest.xml:55:11-70 Error:
        Attribute activity#com.facebook.FacebookActivity@theme value=(@android:style/Theme.Translucent.NoTitleBar) from AndroidManifest.xml:55:11-70
        is also present at [com.facebook.android:facebook-android-sdk:4.17.0] AndroidManifest.xml:32:13-63 value=(@style/com_facebook_activity_theme)
        Suggestion: add 'tools:replace="android:theme"' to <activity> element at AndroidManifest.xml:53:7-56:46 to override
:app:processDebugManifest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute activity#com.facebook.FacebookActivity@theme value=(@android:style/Theme.Translucent.NoTitleBar) from AndroidManifest.xml:55:11-70
        is also present at [com.facebook.android:facebook-android-sdk:4.17.0] AndroidManifest.xml:32:13-63 value=(@style/com_facebook_activity_theme)
        Suggestion: add 'tools:replace="android:theme"' to <activity> element at AndroidManifest.xml:53:7-56:46 to override

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by wayne-kim** [comment]
i read above error message. Suggestion: add 'tools:replace="android:theme"' at D:\LoopyWayne\mobile\workspace\f8app\android\app\src\main\AndroidManifest.xml:55:11-70
So i inputed ' tools:replace="android:theme" '
finally, i builded!!! 
thanks god~~~~~~~~~~~
but My app is say like "WTF! you should demand to president a resignation"
So i will go to demand a resignation to president!
Fuking Geun-hye!!!!!!!!!!!!!!!

**Comment by wayne-kim** [comment]
I was going to install this App to my phone and then I inputted following it.

react-native run-android
adb reverse tcp:8081 tcp:8081
adb reverse tcp:8080 tcp:8080

I installed this App, but It is not working well. 
I can access only login View.
When I clicked "LOG IN WITH FACEBOOK", App show me "Alert [object Object]

Why can not I access more views.

**Comment by katopz** [comment]
I think it's off topic already please close this issue and reopen new one.

**Comment by wayne-kim** [comment]
Where is solution?

**Comment by rendongsc** [comment]
remove
android:theme="@android:style/Theme.Translucent.NoTitleBar"
