### ISSUE TITLE
`npm run import-data` fails with `SyntaxError`

### ISSUE THREAD

**Issue by ugultopu** [fbsamples/f8app#166]
MongoDB is up.
Using Homebrew MongoDB.
Output of `npm start`:
```
> F8v2@0.0.1 start /Users/username/src/react/native/f8app
> babel-node ./server/server.js

Server is now running in development mode on http://localhost:8080
```
Output of `npm run import-data`:
```
> F8v2@0.0.1 import-data /Users/username/src/react/native/f8app
> babel-node ./scripts/import-data-from-parse.js

Loading Speakers
SyntaxError: Unexpected token P in JSON at position 0
    at JSON.parse (<anonymous>)
    at /Users/username/src/react/native/f8app/node_modules/node-fetch/lib/body.js:43:15
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

What might be the problem?

Regards

**Comment by cdkd123** [comment]
https://github.com/fbsamples/f8app/issues/156
this may help

**Comment by ugultopu** [comment]
@cdkd123 Do you know if there is going to be an official fix for this problem?

**Comment by cdkd123** [comment]
@ugultopu ,sorry for late.  i thought this is enviroment config problem, not official code problem. so no official fix.

**Comment by 844755001** [comment]
i have the same problem...

**Comment by byk04712** [comment]
Same problem

**Comment by bonnett89** [comment]
Same problem

**Comment by geoom** [comment]
Try this, replace the entire sample data by this https://github.com/ReactWindows/f8app/blob/data/mongodb/db.zip.

Use it as db location for mongo with `--dbpath` parameter to start mongo service. It worked for me.

**Comment by byk04712** [comment]
I resolved this problem. I just edited `import-data-from-parse.js`.   see below

```
async function importClass(className) {
  console.log('Loading', className);
  //const response = await fetch(`https://api.parse.com/1/classes/${className}`, {
  const response = await fetch(`http://localhost:8080/parse/classes/${className}`, {
    method: 'get',
    // headers: {
      // 'X-Parse-Application-Id': 'R0yDMIKCUyEke2UiadcTBBGd1L5hMBTGJSdBNL3W',
      // 'X-Parse-JavaScript-Key': 'BJ5V0APFMlvmCBPDXl9Mgh3q3dFrs18XkQz6A2bO',
      // 'Content-Type': 'application/json'
    // },
    headers: {
      'X-Parse-Application-Id': 'oss-f8-app-2016',
      'Content-Type': 'application/json'
    }
  });
```
