### ISSUE TITLE
Failed to build ios

### ISSUE THREAD

**Issue by mengxy** [fbsamples/f8app#19]
Installing build/Build/Products/Debug-iphonesimulator/F8v2.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
f8app/node_modules/react-native/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/F8v2.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:464:13)
    at Object.execFileSync (child_process.js:484:13)
    at _runIOS (runIOS.js:83:34)
    at runIOS.js:24:5
    at tryCallTwo (/f8app/node_modules/react-native/node_modules/promise/lib/core.js:45:5)
    at doResolve (/f8app/node_modules/react-native/node_modules/promise/lib/core.js:200:13)
    at new Promise (/f8app/node_modules/react-native/node_modules/promise/lib/core.js:66:3)
    at Array.runIOS (runIOS.js:23:10)
    at Object.run (/f8app/node_modules/react-native/local-cli/cli.js:86:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:88:7)

**Comment by thinkwing** [comment]
I have the same problem as you!

**Comment by mengxy** [comment]
@thinkwing it's a permission issue, I have solved by 
```bash
sudo chmod 777 f8app
```

Don't know whether this is the best practise, open again.

**Comment by iniestano8** [comment]
same problem as you, i've changed the permission, but not works @mengxy

**Comment by iniestano8** [comment]
i missed the pod install step before, and after doing this, it goes well

**Comment by Marenqing** [comment]
I had the same problem.And, I've changed the permission and installed pod.But not works.

**Comment by mathjoy** [comment]
Entry, ":CFBundleIdentifier", Does Not Exist i have the same issue even after pod install

**Comment by Toki-dev** [comment]
Me too.

**Comment by henryzp** [comment]
I also have the same problem。。。and who can tell me how to fix it？

**Comment by FelixZhu** [comment]
I found this error on ruby-2.2.0

After 'rvm use ruby-2.3.0'

Everything is OK!

**Comment by Tiendq** [comment]
Me too :(

pod installed and chmod.
