### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by yinjun322** [fbsamples/f8app#20]
F8v2@0.0.1 start /Users/yinjun/WorkSpace/react_native_workspace/f8app-master
> babel-node ./server/server.js

/Users/yinjun/WorkSpace/react_native_workspace/f8app-master/node_modules/.npminstall/react-native/0.23.1/react-native/Libraries/react-native/react-native.js:120
  ...require('React'),
  ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Module._extensions..js (module.js:405:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/yinjun/WorkSpace/react_native_workspace/f8app-master/node_modules/.npminstall/babel-register/6.7.2/babel-register/lib/node.js:134:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /Users/yinjun/WorkSpace/react_native_workspace/f8app-master/node_modules/.npminstall/babel-core/6.7.6/babel-core/lib/transformation/file/options/option-manager.js:368:22
    at Array.map (native)

node:
5.4.0

**Comment by frantic** [comment]
See https://github.com/fbsamples/f8app/issues/10
