### ISSUE TITLE
Parse Dashboard - Server not reachable: unable to connect to server

### ISSUE THREAD

**Issue by ganlulu2018** [fbsamples/f8app#233]
Hi,
I have tried to go to server parse dashboard (http://localhost:4040/apps/F8/), but it hangs there. And when i tried to access (http://localhost:4040), it shows the F8 is unable to connect to server.
Any steps i miss here?

Thanks.

**Comment by RinatRezyapov** [comment]
Same issue here: 
parse-server doesn't start
Error in console: 
`parse_1            | module.js:491
parse_1            |     throw err;
parse_1            |     ^
parse_1            | 
parse_1            | Error: Cannot find module 'http2'
parse_1            |     at Function.Module._resolveFilename (module.js:489:15)
parse_1            |     at Function.Module._load (module.js:439:25)
parse_1            |     at Module.require (module.js:517:17)
parse_1            |     at require (internal/module.js:11:18)
parse_1            |     at Object.<anonymous> (/usr/local/lib/node_modules/parse-server/node_modules/apn/index.js:15:15)
parse_1            |     at Module._compile (module.js:573:30)
parse_1            |     at Object.Module._extensions..js (module.js:584:10)
parse_1            |     at Module.load (module.js:507:32)
parse_1            |     at tryModuleLoad (module.js:470:12)
parse_1            |     at Function.Module._load (module.js:462:3)
f8app_parse_1 exited with code 1
`
Same error on different versions of node: 8.4, 8.11.3, 10.7.0
Tried to reinstall yarn, node, npm. Tried to install apn, http2 manually. Nothing happens.

**Comment by RinatRezyapov** [comment]
Just added image yongjhih/parse-server instead build. Now it works.
Complete docker-compose.yml
`
version: "3"
services:
  mongo:
    image: mongo
    networks:
      default:
        aliases:
          - mongo
  mongorestore:
    build: ./server/mongorestore
    depends_on:
      - mongo
  parse:
    image: yongjhih/parse-server
    ports:
      - "1337:1337"
    environment:
      PORT: 1337
      DATABASE_URI: mongodb://mongo/dev
      APP_ID: oss-f8-app-2017
      MASTER_KEY: oss-f8-app-2017-mk
    depends_on:
      - mongo
  parse_dashboard:
    build: ./server/parse-dashboard
    ports:
      - "4040:4040"
  graphql:
    build: ./server/graphql
    environment:
      - PARSE_URL=http://parse:1337/parse
    ports:
      - "4000:4000"

`

**Comment by ganlulu2018** [comment]
Hi RinatRezyapov,
Thanks for your reply. I have tried your option but the result is same for me.
I can open the parser dashboard (http://localhost:4040/) but inside it mentions the F8 server not reachable.
Need help on this. TQ

**Comment by RinatRezyapov** [comment]
Ganlulu2018 did you remove docker data before trying this?
http://techstream.org/images/img/Docker-Preference-on-MAC.png
Try to "reset to factory defaults" and then download new f8app repository and launch "yarn server".

**Comment by ganlulu2018** [comment]
Hi RinatRezyapov,
I have tried the method you listed above but the result is same. My console log and parse dashboard are as below. Thanks.

![image](https://user-images.githubusercontent.com/33907060/43201999-c2ecb34e-904c-11e8-9909-81ec56fffb2f.png)

![image](https://user-images.githubusercontent.com/33907060/43202058-ee6ce728-904c-11e8-9b1a-cee2c8e12868.png)

**Comment by sis-dk** [comment]
Any fix for this? I'm facing the same issue. http2 not found.

**Comment by jimmynguyc** [comment]
You'll have to change `server/parse-server/Dockerfile` to use `FROM node:8.11-alpine` due to this problem https://github.com/parse-community/parse-server/issues/4976

After change do 

```
docker-compose down
docker-compose rm
docker rmi f8app_parse
```

And then `yarn server` again

**Comment by jimmynguyc** [comment]
Submitted a PR https://github.com/fbsamples/f8app/pull/234

**Comment by AbhiShrek** [comment]
@jimmynguyc , tried 8.11-alpine, still not working. same error.

**Comment by jimmynguyc** [comment]
@AbhiShrek did you remove the old docker-compose containers and the `f8app_parse` docker image?

```
$ docker-compose down
$ docker-compose rm
$ docker rmi f8app_parse
```

Double check that you don't have anything after running `docker-compose ps`. And there's no `f8app_parse` image when you do `docker images`.

**Comment by yukihirai0505** [comment]
thaks @jimmynguyc 

Your PR should be merged ASAP🤗

**Comment by AbhiShrek** [comment]
@jimmynguyc , yes i did all that, still the same problem.
@RinatRezyapov, It worked the way you mentioned, with yongjhih/parse-server. Thanks !!

**Comment by 0DividebYZer0** [comment]
Hi im having a problem with running the Yarn server. please help with this error
`PS C:\Users\user\f8app> yarn server
yarn run v1.19.1
$ docker-compose up
Building parse_dashboard
Step 1/4 : FROM node:8.4-alpine
 ---> 016382f39a51
Step 2/4 : RUN ["npm", "install", "-g", "parse-dashboard"]
 ---> Running in ff885784e561
npm info it worked if it ends with ok
npm info using npm@5.3.0
npm info using node@v8.4.0
npm http fetch GET 200 https://registry.npmjs.org/parse-dashboard 617ms
npm http fetch GET 200 https://registry.npmjs.org/@babel%2fruntime 146ms
npm http fetch GET 200 https://registry.npmjs.org/graphql 132ms
npm http fetch GET 200 https://registry.npmjs.org/connect-flash 400ms
npm http fetch GET 200 https://registry.npmjs.org/create-react-class 406ms
npm http fetch GET 200 https://registry.npmjs.org/bcryptjs 412ms
npm http fetch GET 200 https://registry.npmjs.org/cookie-session 409ms
npm http fetch GET 200 https://registry.npmjs.org/csurf 405ms
npm http fetch GET 200 https://registry.npmjs.org/commander 428ms
npm http fetch GET 200 https://registry.npmjs.org/copy-to-clipboard 428ms
npm http fetch GET 200 https://registry.npmjs.org/body-parser 439ms
npm http fetch GET 200 https://registry.npmjs.org/express 510ms
npm http fetch GET 200 https://registry.npmjs.org/cookie-session/-/cookie-session-2.0.0-beta.3.tgz 160ms
npm http fetch GET 200 https://registry.npmjs.org/graphql-playground-react 316ms
npm http fetch GET 200 https://registry.npmjs.org/json-file-plus 272ms
npm http fetch GET 200 https://registry.npmjs.org/immutable-devtools 280ms
npm http fetch GET 200 https://registry.npmjs.org/package-json 272ms
npm http fetch GET 200 https://registry.npmjs.org/bcryptjs/-/bcryptjs-2.3.0.tgz 333ms
npm http fetch GET 200 https://registry.npmjs.org/parse 231ms
npm http fetch GET 200 https://registry.npmjs.org/history 357ms
npm http fetch GET 200 https://registry.npmjs.org/passport 235ms
npm http fetch GET 200 https://registry.npmjs.org/js-beautify 380ms
npm http fetch GET 200 https://registry.npmjs.org/immutable 395ms
npm http fetch GET 200 https://registry.npmjs.org/prismjs 154ms
npm http fetch GET 200 https://registry.npmjs.org/passport-local 170ms
npm http fetch GET 200 https://registry.npmjs.org/immutable-devtools/-/immutable-devtools-0.1.3.tgz 193ms
npm http fetch GET 200 https://registry.npmjs.org/query-string 152ms
npm http fetch GET 200 https://registry.npmjs.org/passport/-/passport-0.4.0.tgz 149ms
npm http fetch GET 200 https://registry.npmjs.org/react 180ms
npm http fetch GET 200 https://registry.npmjs.org/immutable/-/immutable-4.0.0-rc.9.tgz 285ms
npm http fetch GET 200 https://registry.npmjs.org/react-dnd-html5-backend 221ms
npm http fetch GET 200 https://registry.npmjs.org/react-helmet 227ms
npm http fetch GET 200 https://registry.npmjs.org/react-dom 251ms
npm http fetch GET 200 https://registry.npmjs.org/react-router 319ms
npm http fetch GET 200 https://registry.npmjs.org/react-dnd 454ms
npm http fetch GET 200 https://registry.npmjs.org/regenerator-runtime 294ms
npm http fetch GET 200 https://registry.npmjs.org/react-router-dom 342ms
npm http fetch GET 200 https://registry.npmjs.org/semver 178ms
npm http fetch GET 200 https://registry.npmjs.org/react-redux 385ms
npm http fetch GET 200 https://registry.npmjs.org/prop-types 1828ms
npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR! 
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-10T10_53_04_755Z-debug.log
ERROR: Service 'parse_dashboard' failed to build: The command 'npm install -g parse-dashboard' returned a non-zero code: 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\user\f8app>`

**Comment by 0DividebYZer0** [comment]
> Hi im having a problem with running the Yarn server. please help with this error
> `PS C:\Users\user\f8app> yarn server
> yarn run v1.19.1
> $ docker-compose up
> Building parse_dashboard
> Step 1/4 : FROM node:8.4-alpine
> ---> 016382f39a51
> Step 2/4 : RUN ["npm", "install", "-g", "parse-dashboard"]
> ---> Running in ff885784e561
> npm info it worked if it ends with ok
> npm info using npm@5.3.0
> npm info using node@v8.4.0
> npm http fetch GET 200 https://registry.npmjs.org/parse-dashboard 617ms
> npm http fetch GET 200 https://registry.npmjs.org/@babel%2fruntime 146ms
> npm http fetch GET 200 https://registry.npmjs.org/graphql 132ms
> npm http fetch GET 200 https://registry.npmjs.org/connect-flash 400ms
> npm http fetch GET 200 https://registry.npmjs.org/create-react-class 406ms
> npm http fetch GET 200 https://registry.npmjs.org/bcryptjs 412ms
> npm http fetch GET 200 https://registry.npmjs.org/cookie-session 409ms
> npm http fetch GET 200 https://registry.npmjs.org/csurf 405ms
> npm http fetch GET 200 https://registry.npmjs.org/commander 428ms
> npm http fetch GET 200 https://registry.npmjs.org/copy-to-clipboard 428ms
> npm http fetch GET 200 https://registry.npmjs.org/body-parser 439ms
> npm http fetch GET 200 https://registry.npmjs.org/express 510ms
> npm http fetch GET 200 https://registry.npmjs.org/cookie-session/-/cookie-session-2.0.0-beta.3.tgz 160ms
> npm http fetch GET 200 https://registry.npmjs.org/graphql-playground-react 316ms
> npm http fetch GET 200 https://registry.npmjs.org/json-file-plus 272ms
> npm http fetch GET 200 https://registry.npmjs.org/immutable-devtools 280ms
> npm http fetch GET 200 https://registry.npmjs.org/package-json 272ms
> npm http fetch GET 200 https://registry.npmjs.org/bcryptjs/-/bcryptjs-2.3.0.tgz 333ms
> npm http fetch GET 200 https://registry.npmjs.org/parse 231ms
> npm http fetch GET 200 https://registry.npmjs.org/history 357ms
> npm http fetch GET 200 https://registry.npmjs.org/passport 235ms
> npm http fetch GET 200 https://registry.npmjs.org/js-beautify 380ms
> npm http fetch GET 200 https://registry.npmjs.org/immutable 395ms
> npm http fetch GET 200 https://registry.npmjs.org/prismjs 154ms
> npm http fetch GET 200 https://registry.npmjs.org/passport-local 170ms
> npm http fetch GET 200 https://registry.npmjs.org/immutable-devtools/-/immutable-devtools-0.1.3.tgz 193ms
> npm http fetch GET 200 https://registry.npmjs.org/query-string 152ms
> npm http fetch GET 200 https://registry.npmjs.org/passport/-/passport-0.4.0.tgz 149ms
> npm http fetch GET 200 https://registry.npmjs.org/react 180ms
> npm http fetch GET 200 https://registry.npmjs.org/immutable/-/immutable-4.0.0-rc.9.tgz 285ms
> npm http fetch GET 200 https://registry.npmjs.org/react-dnd-html5-backend 221ms
> npm http fetch GET 200 https://registry.npmjs.org/react-helmet 227ms
> npm http fetch GET 200 https://registry.npmjs.org/react-dom 251ms
> npm http fetch GET 200 https://registry.npmjs.org/react-router 319ms
> npm http fetch GET 200 https://registry.npmjs.org/react-dnd 454ms
> npm http fetch GET 200 https://registry.npmjs.org/regenerator-runtime 294ms
> npm http fetch GET 200 https://registry.npmjs.org/react-router-dom 342ms
> npm http fetch GET 200 https://registry.npmjs.org/semver 178ms
> npm http fetch GET 200 https://registry.npmjs.org/react-redux 385ms
> npm http fetch GET 200 https://registry.npmjs.org/prop-types 1828ms
> npm ERR! code ENOGIT
> npm ERR! No git binary found in $PATH
> npm ERR!
> npm ERR! Failed using git.
> npm ERR! Please check if you have git installed and in your PATH.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /root/.npm/_logs/2019-11-10T10_53_04_755Z-debug.log
> ERROR: Service 'parse_dashboard' failed to build: The command 'npm install -g parse-dashboard' returned a non-zero code: 1
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> PS C:\Users\user\f8app>`

And if i run the 'npm install -g parse-dashboard' command separately 

`C:\Users\user>npm install -g parse-dashboard
npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN deprecated cryptiles@4.1.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated bfj-node4@5.3.1: Switch to the `bfj` package for fixes and new features!
C:\Users\user\AppData\Roaming\npm\parse-dashboard -> C:\Users\user\AppData\Roaming\npm\node_modules\parse-dashboard\bin\parse-dashboard
npm WARN codemirror-graphql@0.6.12 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-language-service-interface@1.3.2 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-language-service-utils@1.2.2 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-config@2.0.1 requires a peer of graphql@^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-import@0.4.5 requires a peer of graphql@^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphiql@0.11.11 requires a peer of graphql@^0.6.0 || ^0.7.0 || ^0.8.0-b || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-codemirror@1.0.0 requires a peer of react@>=15.5 <16 but none is installed. You must install peer dependencies yourself.
npm WARN react-codemirror@1.0.0 requires a peer of react-dom@>=15.5 <16 but none is installed. You must install peer dependencies yourself.

+ parse-dashboard@2.0.5
updated 1 package in 39.351s

C:\Users\user>`

**Comment by Vimalraj571** [comment]
Try this one https://github.com/nodejs/docker-node/issues/586#issue-273737852 @0DividebYZer0

**Comment by aacassandra** [comment]
any update? i can't still run parse dashboard from my localhost. im using parse server version 6 and parse-dashboard version 5. please help me
