### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by BrnoPCmaniak** [fbsamples/f8app#34]
After downloading f8app.
Sever fails to run.
```
npm start

> F8v2@0.0.1 start /Users/fdobrovolny/workspace/f8
> babel-node ./server/server.js

/Users/fdobrovolny/workspace/f8/node_modules/babel-core/lib/transformation/file/index.js:556
      throw err;
      ^

SyntaxError: /Users/fdobrovolny/workspace/f8/server/server.js: Unexpected token (85:2)
  83 |       users,
  84 |     }, IS_DEVELOPMENT),
> 85 |   );
     |   ^
  86 | }
  87 | 
  88 | server.use(
    at Parser.pp.raise (/Users/fdobrovolny/workspace/f8/node_modules/babylon/index.js:1378:13)
    at Parser.pp.unexpected (/Users/fdobrovolny/workspace/f8/node_modules/babylon/index.js:2817:8)
    at Parser.pp.parseExprAtom (/Users/fdobrovolny/workspace/f8/node_modules/babylon/index.js:749:12)
    at Parser.pp.parseExprSubscripts (/Users/fdobrovolny/workspace/f8/node_modules/babylon/index.js:504:19)
    at Parser.pp.parseMaybeUnary (/Users/fdobrovolny/workspace/f8/node_modules/babylon/index.js:484:19)

npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/fdobrovolny/.nvm/versions/node/v6.0.0/bin/node" "/Users/fdobrovolny/.nvm/versions/node/v6.0.0/bin/npm" "start"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! F8v2@0.0.1 start: `babel-node ./server/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the F8v2@0.0.1 start script 'babel-node ./server/server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the F8v2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node ./server/server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs F8v2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls F8v2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
```
[npm-debug.log.txt](https://github.com/fbsamples/f8app/files/248699/npm-debug.log.txt)

**Comment by BrnoPCmaniak** [comment]
I have copied all files without .* ones now everything works just fine.

**Comment by hzhilt** [comment]
Can you give the detail?
