### ISSUE TITLE
 ERROR  watch... ENOSPC

### ISSUE THREAD

**Issue by QuoniamYIF** [fbsamples/f8app#55]
my system is android 4.4.4.

 i use `react-native start`,but there are some problems,who can tell me why?

thank you very much.

```
 ERROR  watch /home/quoniam/myRNStudy/f8app/node_modules/react-native-linear-gradient/android/build/intermediates/exploded-aar/com.android.support/appcompat-v7/23.0.1/res/values-pl ENOSPC
{"code":"ENOSPC","errno":"ENOSPC","syscall":"watch /home/quoniam/myRNStudy/f8app/node_modules/react-native-linear-gradient/android/build/intermediates/exploded-aar/com.android.support/appcompat-v7/23.0.1/res/values-pl","filename":"/home/quoniam/myRNStudy/f8app/node_modules/react-native-linear-gradient/android/build/intermediates/exploded-aar/com.android.support/appcompat-v7/23.0.1/res/values-pl"}
Error: watch /home/quoniam/myRNStudy/f8app/node_modules/react-native-linear-gradient/android/build/intermediates/exploded-aar/com.android.support/appcompat-v7/23.0.1/res/values-pl ENOSPC
    at exports._errnoException (util.js:953:11)
    at FSWatcher.start (fs.js:1423:19)
    at Object.fs.watch (fs.js:1450:11)
    at NodeWatcher.watchdir (/home/quoniam/myRNStudy/f8app/node_modules/sane/src/node_watcher.js:144:20)
    at Walker.<anonymous> (/home/quoniam/myRNStudy/f8app/node_modules/sane/src/node_watcher.js:353:12)
    at emitTwo (events.js:106:13)
    at Walker.emit (events.js:191:7)
    at /home/quoniam/myRNStudy/f8app/node_modules/walker/lib/walker.js:69:16
    at /home/quoniam/myRNStudy/f8app/node_modules/graceful-fs/graceful-fs.js:142:16
    at /home/quoniam/myRNStudy/f8app/node_modules/graceful-fs/graceful-fs.js:142:16
```

**Comment by ask007java** [comment]
I am using Ubuntu and getting same error. Were you able to fix it ?

**Comment by QuoniamYIF** [comment]
@ask007java this maybe  the problem of watchman.it has watched too many file.if it is,cancel the limit

**Comment by grit96** [comment]
Without using watchman, this can be fixed by increasing the number of inotify watches using `echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

**Comment by cyberhck** [comment]
@grit96 You saved my day, was about to go back to native android away from react stuff :)

**Comment by exequieldemaio** [comment]
@grit96 thank you

**Comment by smna15** [comment]
@grit96 AWESOME! I've been looking for the whole day to fix it!

**Comment by elderSword** [comment]
@grit96 thank you

**Comment by porta8080** [comment]
@grit96  you sir is a real genious. does anyone know the cause of this problem? error always occur in differente packages for me eveytime it happens (if I don't reboot, it won't stop). @grit96 answer solved the problem

**Comment by aitchkhan** [comment]
Saved my day, Thanks.  @grit96

**Comment by quoniammm** [comment]
the problem is solved.so i closed this issue.

**Comment by iboxgithub** [comment]
Thank you SO MUCH

**Comment by nehapraksh** [comment]
Thanks a lot !

**Comment by NourBesbes** [comment]
Thanks :+1:

**Comment by prakasa1904** [comment]
awesome, thanks a lot

**Comment by m30do** [comment]
@grit96 Great

**Comment by valentinancy** [comment]
thanks hehe

**Comment by johnreytanquinco** [comment]
perfect! :D Thanks you @grit96 !

**Comment by bas-innovations** [comment]
**@grit96** Worked for me. Thanks!

**Comment by senowijayanto** [comment]
Thanks @grit96

**Comment by mistryhiren94** [comment]
thanks @grit96

**Comment by akshayaggarwal99** [comment]
Thanks @grit96

**Comment by jayskie712** [comment]
thanks.. ur a great help men @grit96

**Comment by manoj-thrymr** [comment]
Thanks @grit96

**Comment by defoishugo** [comment]
Thanks @grit96 ! :+1:

**Comment by mobihack** [comment]
Thanks @grit96 :+1: :heart: :heart_eyes:

**Comment by srpalomino** [comment]
Thank you!!!!!

**Comment by Ialimijoro** [comment]
Thanks a lot @grit96

**Comment by InsomniacSabbir** [comment]
@grit96  you are a lifesaver ... thanks!!!

**Comment by ahmedtehseen** [comment]
Thanks @grit96

**Comment by simo97** [comment]
@grit96 you are a legend thanks dude !!!

**Comment by ujjwalagrawal17** [comment]
@grit96 Thanks. Works perfectly.

**Comment by aquibyatoo** [comment]
thanx buddy

**Comment by at-thachnguyen2** [comment]
thanks a lot

**Comment by christopherganda** [comment]
@grit96 You saved my day! Thanks bruh

**Comment by hiralicubes** [comment]
@grit96 
Thanks a lot!

**Comment by escalepion** [comment]
You are hero, you are Chuck Norris, you are Superman without tights !!!

**Comment by piyurabadiya** [comment]
@grit96  You saved my day...Thanks a lot

**Comment by wicaker** [comment]
> Without using watchman, this can be fixed by increasing the number of inotify watches using `echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

Thank you [grit96](/grit96) you save my life

**Comment by JRSgit** [comment]
@grit96  Muito Obrigado, 
thank you very much

**Comment by srikanthguttula** [comment]
> Without using watchman, this can be fixed by increasing the number of inotify watches using `echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

after executing this command the error gone
tq

**Comment by alemkhodadadi** [comment]
@grit96 you saved my day man! thanks

**Comment by Awadhesh786** [comment]
> I am using Ubuntu and getting same error. Were you able to fix it ?

same to you

**Comment by harimhetre** [comment]
> Without using watchman, this can be fixed by increasing the number of inotify watches using `echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

This works for me...thanks a lot man

**Comment by bhayward93** [comment]
Much appreciated @grit96

**Comment by acaciomartins** [comment]
Tks!!!

**Comment by ShailTiwari** [comment]
This worked for me...thanks
