### ISSUE TITLE
npm start - Cannot find module 'parse-server' error

### ISSUE THREAD

**Issue by prashannth** [fbsamples/f8app#65]
> F8v2@0.0.1 start /Users/Prash/Downloads/Kitchen/f8app
> babel-node ./server/server.js

module.js:442
    throw err;
    ^

Error: Cannot find module 'parse-server'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (server.js:28:1)
    at Module._compile (module.js:541:32)
    at loader (/Users/Mac/Downloads/f8app/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js](/Users/Mac/Downloads/f8app/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
[npm-debug.txt](https://github.com/fbsamples/f8app/files/299283/npm-debug.txt)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.2.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! F8v2@0.0.1 start: `babel-node ./server/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the F8v2@0.0.1 start script 'babel-node ./server/server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the F8v2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node ./server/server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs F8v2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls F8v2
npm ERR! There is likely additional logging output above.

**Comment by hydewang** [comment]
I have encountered the same error

**Comment by hydewang** [comment]
For me it work, react-native start instead of npm start.
